version: '3'
services:
  psql_postgis_db:
    image: kartoza/postgis:latest
    volumes:
      - ./postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis_admin    # Here it's important to keep the same name as the one configured inside ops_settings_docker.yml
      - POSTGRES_PASS=admin        # Here it's important to keep the same name as the one configured inside ops_settings_docker.yml
      - POSTGRES_DBNAME=gis        # Here it's important to keep the same name as the one configured inside ops_settings_docker.yml
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5434:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=4GB"
    restart: on-failure
    mem_limit: 3000m

  econav:
    build: Dockerfile
    container_name: application
    ports:
      - 8080:3000
    environment:
      DB_USER: gis_admin
      DB_PASSWORD: admin
      DB_URL: postgress://test_user:123@db:5432/docker
      MAPBOX_TOKEN: #write your token
    restart: always

