version: '3'
services:
  psql_postgis_db:
    image: kartoza/postgis:latest
    volumes:
      - ./postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=gis_admin
      - POSTGRES_PASS=admin
      - POSTGRES_DBNAME=gis
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5434:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=4GB"
    restart: on-failure
    mem_limit: 3000m

  econav:
    build: Dockerfile
    container_name: application
    ports:
      - 8080:3000
    environment:
      DB_URL: jdbc:postgresql://localhost:5434/gis
      MAPBOX_TOKEN: #write your token
    restart: always

